[local]
localhost

[mongodb]
mongodb.lpdaws.online

[redis]
redis.lpdaws.online

[mysql]
mysql.lpdaws.online

[rabbitmq]
rabbitmq.lpdaws.online

[catalogue]
catalogue.lpdaws.online

[user]
user.lpdaws.online

[cart]
cart.lpdaws.online

[shipping]
shipping.lpdaws.online

[payment]
payment.lpdaws.online

[frontend]
frontend.lpdaws.online

